version: "3.7"

services:
  database:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rest_api_course
    volumes:
      - ./volumes/pgdata:/data/postgres
